### ISSUE TITLE
Define what should the kitchen have

### ISSUE THREAD

**Issue by erebrus** [erebrus/ggo2023#11]
Before we list what assets we will need for the kitchen, we will need to figure out what will actually be there. Is there any other  object to interact with besides the cauldron? I guess maybe a scale also?

**Comment by erebrus** [comment]
@forager-pixel  and @discolexia , what do you think here? We should try to define wha we need in the kitchen. In terms of functional object, we have the cauldron. Do you think we need something else? Like a prepping table? What about the recipe? Where is it? How do we get to it? Is it something in the UI only? Or do we have an object to interact with in the kitchen that pops up the recipe with the haiku?

**Comment by discolexia** [comment]
Kitchen list:
- Cauldron
- prep table
- grinding bowl
- cutting board
- knife
- bowl for mixing
- bucket/cup for water/milk
- recipe book stand with the open book on it

Skelly approaches the book stand, the recipe pop up on the screen, and player can click on ingredient to get a haiku. 
once he got the right ingredient done and tossed in the pot, the ingredient get crossed out from the recipe 
? to add scale to context, what kind of extra pages should i make in the cook book for player to compare?

**Comment by erebrus** [comment]
for the prototype we will have only cauldron and prep table.
