### ISSUE TITLE
Define transition area

### ISSUE THREAD

**Issue by erebrus** [erebrus/ggo2023#7]
Should we have portals to let the player go to the biomes, or should we have transitional areas, for instance, 4 doors out of the dungeon/castle each leading to a different biome.

**Comment by erebrus** [comment]
@forager-pixel and @discolexia , can you give feedback on this? If we don't go for the portals, then we need to define a transition area. I'm tempted to just do portals.. What do you think?

**Comment by discolexia** [comment]
i think portals would work, it's easier, magical and it just works

**Comment by discolexia** [comment]
also, if we gonna make a well in one of the biomes, maybe we can have the same wells but make them look magical as a door to biomes? just an idea to reuse assets

**Comment by erebrus** [comment]
ok, so we will go for a second room with portals
